MOUSEKEY_ENABLE = yes     # Mouse keys
REPEAT_KEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
VIA_ENABLE = no
LTO_ENABLE = yes

QUANTUM_PAINTER_ENABLE = no
OLED_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE  = no
